### ISSUE TITLE
Option to automatically regenerate expired tokens

### ISSUE THREAD

**Issue by MrGossett** [zabawaba99/fireauth#3]
[Firebase tokens expire 24 hours after they're created, unless an explicit expiration is set](https://www.firebase.com/docs/web/guide/login/custom.html#section-rest-token-generation). Fireauth can anticipate the expiration of any token it generates. It would be useful if fireauth also had a mechanism to generate new tokens on-demand (to replace an expired token).

This might be accomplished by providing something like `func (*Generator) CreateTokenWithRefresh(Data, *Option) (string, chan string, error)` which returns a generated token along with a `chan string` that will publish a new token when the previous token expires. Implementers would then end up doing something like this:

``` go
auth := fireauth.New(mySecret)

token, refresher, _ := auth.CreateTokenWithRefresh(data, options)

// later on...
select {
case refreshedToken <- refresher:
    token = refreshedToken
default:
}
// carry on using token
```

A possible (and untested) implementation of `CreateTokenWithRefresh`:

``` go
func (t *Generator) CreateTokenWithRefresh(data Data, options *Option) (string, chan string, error) {
    token, err := t.CreateToken(data, options)
    if err != nil {
        return "", nil, err
    }

    c := make(chan string)
    duration := time.Unix(options.Expiration, 0).Sub(time.Now())
    ticker := time.NewTicker(duration)

    go func() {
        for _ = range <-ticker.C {
            newToken, err := t.CreateToken(data, options)
            if err != nil {
                close(c)
                ticker.Stop()
                return
            }
            c <- newToken
        }
    }()

    return token, c, nil
}
```

**Comment by zabawaba99** [comment]
>  Fireauth can anticipate the expiration of any token it generates. It would be useful if fireauth also had a mechanism to generate new tokens on-demand (to replace an expired token).

While I think that is a pretty neat feature, I think that it is beyond the scope of Fireauth. That feels more like consumer logic than library logic.

@tonkpils thoughts?
