### ISSUE TITLE
the behavior of sign() seems wrong

### ISSUE THREAD

**Issue by hsinhoyeh** [zabawaba99/fireauth#6]
please noted that the behavior of h.Write([]byte{...}) and h.Sum([]byte{...}) are different,
you can check this example: https://play.golang.org/p/y7S52DdL_T

in Sum(data), it actually appends the checksum AFTER the byte data.
https://golang.org/src/crypto/sha256/sha256.go?s=1643:1663#L128

however, the following code snippet works fine for me

```
@@ -136,5 +138,7 @@ func encode(data []byte) string {
 }
 func sign(message, secret string) string {
-       return encode(hmac.New(sha256.New, []byte(secret)).Sum([]byte(message)))
+       h := hmac.New(sha256.New, []byte(secret))
+       h.Write([]byte(message))
+       return encode(h.Sum(nil))
 }
```

I would like to send a PR, any concerns?

**Comment by zabawaba99** [comment]
It looks like this change was introduced in a [former PR](https://github.com/CloudCom/fireauth/pull/4/files#diff-18f04d9ad3369192f1154eb2a981af41L143).

Reading the [`hash.Hash`](https://golang.org/pkg/hash/#Hash) documentation for `Sum`:

> // Sum appends the current hash to b and returns the resulting slice.
> // It does not change the underlying hash state.

Looks like you're spot on with your changeset. My only concern would be checking against regressions. It looks like the tests aren't beefed up enough to ensure this doesn't break again. If you could add some tests in for this along with the change to `sign` that would be great!
